[project]
name = "firecrawl-smolagents-deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-search-results>=2.4.2",
    "python-dotenv>=1.2.1",
    "smolagents[litellm,mcp,openai]>=1.23.0",
]
